// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagementSystem.Models;

namespace SchoolManagementSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200329172730_UpdatedExpenseFK")]
    partial class UpdatedExpenseFK
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.Annual", b =>
                {
                    b.Property<int>("AnnualId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Fees")
                        .HasColumnType("float");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ProgrameId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AnnualId");

                    b.HasIndex("ProgrameId");

                    b.HasIndex("UserId");

                    b.ToTable("Annuals");

                    b.HasData(
                        new
                        {
                            AnnualId = 1,
                            Description = "This is the one year School",
                            Fees = 18000.0,
                            IsActive = true,
                            ProgrameId = 1,
                            Title = "July-May",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("AttendanceTime")
                        .HasColumnType("time");

                    b.Property<int>("ClassTblId")
                        .HasColumnType("int");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("AttendanceId");

                    b.HasIndex("ClassTblId");

                    b.HasIndex("SessionId");

                    b.HasIndex("StudentId");

                    b.ToTable("Attendances");

                    b.HasData(
                        new
                        {
                            AttendanceId = 1,
                            AttendanceDate = new DateTime(2016, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AttendanceTime = new TimeSpan(0, 12, 15, 6, 0),
                            ClassTblId = 1,
                            SessionId = 1,
                            StudentId = 1
                        });
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.ClassSubject", b =>
                {
                    b.Property<int>("ClassSubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClassTblId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("ClassSubjectId");

                    b.HasIndex("ClassTblId");

                    b.HasIndex("SubjectId");

                    b.ToTable("ClassSubjects");

                    b.HasData(
                        new
                        {
                            ClassSubjectId = 1,
                            ClassTblId = 1,
                            IsActive = true,
                            Name = "Math",
                            SubjectId = 1
                        });
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.ClassTbl", b =>
                {
                    b.Property<int>("ClassTblId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClassTblId");

                    b.ToTable("ClassTbls");

                    b.HasData(
                        new
                        {
                            ClassTblId = 1,
                            IsActive = true,
                            Name = "High School"
                        });
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.Designation", b =>
                {
                    b.Property<int>("DesignationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DesignationId");

                    b.HasIndex("UserId");

                    b.ToTable("Designations");

                    b.HasData(
                        new
                        {
                            DesignationId = 1,
                            IsActive = true,
                            Title = "Principal",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.EmployeeCertification", b =>
                {
                    b.Property<int>("EmployeeCertificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CertificateName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CertificationAuthority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeResumeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FromYear")
                        .HasColumnType("datetime2");

                    b.Property<string>("LevelCertification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeCertificationId");

                    b.HasIndex("EmployeeResumeId");

                    b.HasIndex("UserId");

                    b.ToTable("EmployeeCertifications");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.EmployeeEducation", b =>
                {
                    b.Property<int>("EmployeeEducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeResumeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FromYear")
                        .HasColumnType("datetime2");

                    b.Property<string>("Institute")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstituteCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstituteCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleOfDiploma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ToYear")
                        .HasColumnType("datetime2");

                    b.Property<string>("University")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeEducationId");

                    b.HasIndex("EmployeeResumeId");

                    b.ToTable("EmployeeEducations");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.EmployeeLanguage", b =>
                {
                    b.Property<int>("EmployeeLanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmployeeResumeId")
                        .HasColumnType("int");

                    b.Property<string>("LanguageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proficiency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeLanguageId");

                    b.HasIndex("EmployeeResumeId");

                    b.HasIndex("UserId");

                    b.ToTable("EmployeeLanguages");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.EmployeeLeaving", b =>
                {
                    b.Property<int>("EmployeeLeavingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LeavingComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LeavingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LeavingReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeLeavingId");

                    b.HasIndex("StaffId");

                    b.HasIndex("UserId");

                    b.ToTable("EmployeeLeaving");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.EmployeeResume", b =>
                {
                    b.Property<int>("EmployeeResumeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EducationLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacebookProfile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedInProfile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeResumeId");

                    b.ToTable("EmployeeResumes");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.EmployeeSalary", b =>
                {
                    b.Property<int>("EmployeeSalaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SalaryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SalaryMonth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalaryYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeSalaryId");

                    b.HasIndex("StaffId");

                    b.HasIndex("UserId");

                    b.ToTable("EmployeeSalarys");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.EmployeeSkill", b =>
                {
                    b.Property<int>("EmployeeSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmployeeResumeId")
                        .HasColumnType("int");

                    b.Property<string>("SkillName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeSkillId");

                    b.HasIndex("EmployeeResumeId");

                    b.HasIndex("UserId");

                    b.ToTable("EmployeeSkills");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.EmployeeWorkExperience", b =>
                {
                    b.Property<int>("EmployeeWorkExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeResumeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FromYear")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ToYear")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeWorkExperienceId");

                    b.HasIndex("EmployeeResumeId");

                    b.HasIndex("UserId");

                    b.ToTable("EmployeeWorkExperiences");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.EventTbl", b =>
                {
                    b.Property<int>("EventTblId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EventTblId");

                    b.HasIndex("UserId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            EventTblId = 1,
                            Description = "This is technical Workshop",
                            EventDate = new DateTime(2020, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventTitle = "Tech Workshop",
                            Location = "Delhi",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.Exam", b =>
                {
                    b.Property<int>("ExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ExamId");

                    b.HasIndex("UserId");

                    b.ToTable("Exams");

                    b.HasData(
                        new
                        {
                            ExamId = 1,
                            Description = "",
                            EndDate = new DateTime(2016, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2016, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mid Term Exam",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.ExamMark", b =>
                {
                    b.Property<int>("ExamMarkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClassSubjectId")
                        .HasColumnType("int");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<int>("ObtainMarks")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TotalMarks")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ExamMarkId");

                    b.HasIndex("ClassSubjectId");

                    b.HasIndex("ExamId");

                    b.HasIndex("StudentId");

                    b.HasIndex("UserId");

                    b.ToTable("ExamMarks");

                    b.HasData(
                        new
                        {
                            ExamMarkId = 1,
                            ClassSubjectId = 1,
                            ExamId = 1,
                            ObtainMarks = 1,
                            StudentId = 1,
                            TotalMarks = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.Expense", b =>
                {
                    b.Property<int>("ExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("ExpensesDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpensesTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ExpenseId");

                    b.HasIndex("UserId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.ExpenseType", b =>
                {
                    b.Property<int>("ExpenseTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ExpenseId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExpenseTypeId");

                    b.HasIndex("ExpenseId");

                    b.ToTable("ExpenseTypes");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.Programe", b =>
                {
                    b.Property<int>("ProgrameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ProgrameId");

                    b.HasIndex("UserId");

                    b.ToTable("Programes");

                    b.HasData(
                        new
                        {
                            ProgrameId = 1,
                            IsActive = true,
                            Name = "MCA",
                            StartDate = new DateTime(2016, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.ProgrameSession", b =>
                {
                    b.Property<int>("ProgrameSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProgrameId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ProgrameSessionId");

                    b.HasIndex("ProgrameId");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("ProgrameSessions");

                    b.HasData(
                        new
                        {
                            ProgrameSessionId = 1,
                            Description = "ijklmnop",
                            Details = "abcdefgh",
                            ProgrameId = 1,
                            RegDate = new DateTime(2016, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SessionId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.SchoolLeaving", b =>
                {
                    b.Property<int>("SchoolLeavingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClassTblId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LeavingComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LeavingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LeavingReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SchoolLeavingId");

                    b.HasIndex("ClassTblId");

                    b.HasIndex("StudentId");

                    b.HasIndex("UserId");

                    b.ToTable("SchoolLeavings");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.Section", b =>
                {
                    b.Property<int>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SectionId");

                    b.HasIndex("UserId");

                    b.ToTable("Sections");

                    b.HasData(
                        new
                        {
                            SectionId = 1,
                            Name = "A",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.Session", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");

                    b.HasData(
                        new
                        {
                            SessionId = 1,
                            EndDate = new DateTime(2016, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "July",
                            StartDate = new DateTime(2016, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AnyCriminalOffence")
                        .HasColumnType("bit");

                    b.Property<double>("BasicSalary")
                        .HasColumnType("float");

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CriminalOffenceDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DesignationId")
                        .HasColumnType("int");

                    b.Property<string>("DisabilityDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DoYouHaveAnyDisability")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomePhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MedicationDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TakingAnyMedication")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("photo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StaffId");

                    b.HasIndex("DesignationId");

                    b.HasIndex("UserId");

                    b.ToTable("Staffs");

                    b.HasData(
                        new
                        {
                            StaffId = 1,
                            Address = "Allahabad",
                            AnyCriminalOffence = false,
                            BasicSalary = 25000.0,
                            ContactNo = "1234567890",
                            Description = "Completed PHd from MNNIT Allahabad",
                            DesignationId = 0,
                            DoYouHaveAnyDisability = false,
                            Email = "rahulmishra@gmail.com",
                            Gender = "male",
                            HomePhone = "8652544148",
                            IsActive = true,
                            Name = "Rahul Mishra",
                            Qualification = "P.Hd",
                            RegistrationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TakingAnyMedication = false,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.StaffAttendance", b =>
                {
                    b.Property<int>("StaffAttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("ClosingTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("ComingTime")
                        .HasColumnType("time");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.HasKey("StaffAttendanceId");

                    b.HasIndex("StaffId");

                    b.ToTable("StaffAttendances");

                    b.HasData(
                        new
                        {
                            StaffAttendanceId = 1,
                            AttendanceDate = new DateTime(2016, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClosingTime = new TimeSpan(0, 1, 15, 6, 0),
                            ComingTime = new TimeSpan(0, 12, 15, 6, 0),
                            StaffId = 1
                        });
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AadharNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AdmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cast")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClassTblId")
                        .HasColumnType("int");

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuardianName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuardianOccupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuardianPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PreviousPercentage")
                        .HasColumnType("real");

                    b.Property<string>("PreviousSchool")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProgrameId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Religion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.HasIndex("ClassTblId");

                    b.HasIndex("ProgrameId");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            AadharNo = "1234567890",
                            Address = "Varanasi",
                            AdmissionDate = new DateTime(2020, 3, 29, 22, 57, 27, 802, DateTimeKind.Local).AddTicks(2097),
                            ClassTblId = 1,
                            ContactNo = "8652544148",
                            DateOfBirth = new DateTime(1994, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ausantoshsingh@gmail.com",
                            FatherName = "C. B. Singh",
                            Gender = "Male",
                            Name = "Santosh Singh",
                            Photo = "",
                            PreviousPercentage = 70f,
                            PreviousSchool = "MIIT Varanasi",
                            ProgrameId = 1,
                            SessionId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.StudentPromote", b =>
                {
                    b.Property<int>("StudentPromoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnnualFee")
                        .HasColumnType("int");

                    b.Property<int>("ClassTblId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSubmit")
                        .HasColumnType("bit");

                    b.Property<int>("ProgrameSessionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PromoteDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("StudentPromoteId");

                    b.HasIndex("ClassTblId");

                    b.HasIndex("ProgrameSessionId");

                    b.HasIndex("SectionId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentPromotes");

                    b.HasData(
                        new
                        {
                            StudentPromoteId = 1,
                            AnnualFee = 10000,
                            ClassTblId = 1,
                            IsActive = false,
                            IsSubmit = false,
                            ProgrameSessionId = 1,
                            PromoteDate = new DateTime(2016, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SectionId = 0,
                            StudentId = 1
                        });
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalMarks")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SubjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            SubjectId = 1,
                            Description = "Computer Networks is one the most important subject in Computer Science.",
                            Name = "Computer Networks",
                            RegDate = new DateTime(2016, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalMarks = 80,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.SubmissionFee", b =>
                {
                    b.Property<int>("SubmissionFeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("ClassTblId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeeMonth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProgrameId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SubmissionFeeId");

                    b.HasIndex("ClassTblId");

                    b.HasIndex("ProgrameId");

                    b.HasIndex("StudentId");

                    b.HasIndex("UserId");

                    b.ToTable("SubmissionFees");

                    b.HasData(
                        new
                        {
                            SubmissionFeeId = 1,
                            Amount = 60000.0,
                            ClassTblId = 1,
                            Description = "This is Jan month fee",
                            FeeMonth = "January",
                            ProgrameId = 1,
                            StudentId = 1,
                            SubmissionDate = new DateTime(2016, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.TimeTable", b =>
                {
                    b.Property<int>("TimeTableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClassSubjectId")
                        .HasColumnType("int");

                    b.Property<string>("Day")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TimeTableId");

                    b.HasIndex("ClassSubjectId");

                    b.HasIndex("StaffId");

                    b.HasIndex("UserId");

                    b.ToTable("TimeTables");

                    b.HasData(
                        new
                        {
                            TimeTableId = 1,
                            ClassSubjectId = 1,
                            Day = "Saturday",
                            EndTime = new TimeSpan(0, 12, 55, 6, 0),
                            IsActive = true,
                            StaffId = 1,
                            StartTime = new TimeSpan(0, 12, 15, 6, 0),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserTypeId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("UserTypeId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Address = "Varanasi",
                            ContactNo = "8652544148",
                            Email = "ausantoshsingh@gmail.com",
                            FullName = "Santosh Singh",
                            Password = "sks@123",
                            UserName = "ausantoshsingh@gmail.com",
                            UserTypeId = 1
                        });
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.UserType", b =>
                {
                    b.Property<int>("UserTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserTypeId");

                    b.HasIndex("TypeName")
                        .IsUnique()
                        .HasFilter("[TypeName] IS NOT NULL");

                    b.ToTable("UserTypes");

                    b.HasData(
                        new
                        {
                            UserTypeId = 1,
                            Description = "xyz",
                            TypeName = "Admin"
                        });
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.Annual", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Entities.Programe", "Programe")
                        .WithMany("Annuals")
                        .HasForeignKey("ProgrameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystem.Models.Entities.User", "User")
                        .WithMany("Annuals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.Attendance", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Entities.ClassTbl", "ClassTbl")
                        .WithMany("Attendances")
                        .HasForeignKey("ClassTblId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystem.Models.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystem.Models.Entities.Student", "Student")
                        .WithMany("Attendances")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.ClassSubject", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Entities.ClassTbl", "ClassTbl")
                        .WithMany("ClassSubjects")
                        .HasForeignKey("ClassTblId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystem.Models.Entities.Subject", "Subject")
                        .WithMany("ClassSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.Designation", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Entities.User", "User")
                        .WithMany("Designations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.EmployeeCertification", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Entities.EmployeeResume", "EmployeeResume")
                        .WithMany("EmployeeCertifications")
                        .HasForeignKey("EmployeeResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystem.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.EmployeeEducation", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Entities.EmployeeResume", "EmployeeResume")
                        .WithMany("EmployeeEducations")
                        .HasForeignKey("EmployeeResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.EmployeeLanguage", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Entities.EmployeeResume", "EmployeeResume")
                        .WithMany("EmployeeLanguages")
                        .HasForeignKey("EmployeeResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystem.Models.Entities.User", "User")
                        .WithMany("EmployeeLanguages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.EmployeeLeaving", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Entities.Staff", "Staff")
                        .WithMany("EmployeeLeavings")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystem.Models.Entities.User", "User")
                        .WithMany("EmployeeLeavings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.EmployeeSalary", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Entities.Staff", "Staff")
                        .WithMany("EmployeeSalaries")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystem.Models.Entities.User", "User")
                        .WithMany("EmployeeSalaries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.EmployeeSkill", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Entities.EmployeeResume", "EmployeeResume")
                        .WithMany("EmployeeSkills")
                        .HasForeignKey("EmployeeResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystem.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.EmployeeWorkExperience", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Entities.EmployeeResume", "EmployeeResume")
                        .WithMany("EmployeeWorkExperiences")
                        .HasForeignKey("EmployeeResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystem.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.EventTbl", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Entities.User", "User")
                        .WithMany("EventTbls")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.Exam", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Entities.User", "User")
                        .WithMany("Exams")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.ExamMark", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Entities.ClassSubject", "ClassSubject")
                        .WithMany("ExamMarks")
                        .HasForeignKey("ClassSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystem.Models.Entities.Exam", "Exam")
                        .WithMany("ExamMarks")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystem.Models.Entities.Student", "Student")
                        .WithMany("ExamMarks")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystem.Models.Entities.User", "User")
                        .WithMany("ExamMarks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.Expense", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Entities.User", "User")
                        .WithMany("Expenses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.ExpenseType", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Entities.Expense", "Expense")
                        .WithMany("ExpenseTypes")
                        .HasForeignKey("ExpenseId");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.Programe", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Entities.User", "User")
                        .WithMany("Programes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.ProgrameSession", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Entities.Programe", "Programe")
                        .WithMany("ProgrameSessions")
                        .HasForeignKey("ProgrameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystem.Models.Entities.Session", "Session")
                        .WithMany("ProgrameSessions")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystem.Models.Entities.User", "User")
                        .WithMany("ProgrameSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.SchoolLeaving", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Entities.ClassTbl", "ClassTbl")
                        .WithMany("SchoolLeavings")
                        .HasForeignKey("ClassTblId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystem.Models.Entities.Student", "Student")
                        .WithMany("SchoolLeavings")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystem.Models.Entities.User", "User")
                        .WithMany("SchoolLeavings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.Section", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Entities.User", "User")
                        .WithMany("Sections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.Session", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.Staff", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Entities.Designation", "Designation")
                        .WithMany("Staffs")
                        .HasForeignKey("DesignationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystem.Models.Entities.User", "User")
                        .WithMany("Staffs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.StaffAttendance", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Entities.Staff", "Staff")
                        .WithMany("StaffAttendances")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.Student", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Entities.ClassTbl", "ClassTbl")
                        .WithMany("Students")
                        .HasForeignKey("ClassTblId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystem.Models.Entities.Programe", "Programe")
                        .WithMany("Students")
                        .HasForeignKey("ProgrameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystem.Models.Entities.Session", "Session")
                        .WithMany("Students")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystem.Models.Entities.User", "User")
                        .WithMany("Students")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.StudentPromote", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Entities.ClassTbl", "ClassTbl")
                        .WithMany("StudentPromotes")
                        .HasForeignKey("ClassTblId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystem.Models.Entities.ProgrameSession", "ProgrameSession")
                        .WithMany("StudentPromotes")
                        .HasForeignKey("ProgrameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystem.Models.Entities.Section", "Section")
                        .WithMany("StudentPromotes")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystem.Models.Entities.Student", "Student")
                        .WithMany("StudentPromotes")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.Subject", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Entities.User", "User")
                        .WithMany("Subjects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.SubmissionFee", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Entities.ClassTbl", "ClassTbl")
                        .WithMany("SubmissionFees")
                        .HasForeignKey("ClassTblId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystem.Models.Entities.Programe", "Programe")
                        .WithMany("SubmissionFees")
                        .HasForeignKey("ProgrameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystem.Models.Entities.Student", "Student")
                        .WithMany("SubmissionFees")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystem.Models.Entities.User", "User")
                        .WithMany("SubmissionFees")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.TimeTable", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Entities.ClassSubject", "ClassSubject")
                        .WithMany("TimeTables")
                        .HasForeignKey("ClassSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystem.Models.Entities.Staff", "Staff")
                        .WithMany("TimeTables")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystem.Models.Entities.User", "User")
                        .WithMany("TimeTables")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Entities.User", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Entities.UserType", "UserType")
                        .WithMany("Users")
                        .HasForeignKey("UserTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
